name: Build

on:
  push:
    branches:
      - v3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.13, 1.15, 1.16]
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/checkout@v2
        name: Checkout client specifications
        with:
          repository: Unleash/client-specification
          ref: refs/tags/v3.3.1
          path: testdata/client-specification
      - uses: actions/setup-go@v2
        name: Setup go
        with:
          go-version: ${{ matrix.version }}
      - name: Get deps
        run: go get -t -v ./...
      - name: Go vet
        run: go vet ./...
      - name: Run all tests
        run: go test -race -covermode atomic -coverprofile=profile.cov -v ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.version }}
          parallel: true